### ISSUE TITLE
Ignores fieldsets

### ISSUE THREAD

**Issue by mataski** [sharazam/printpdf#102]
Prints everything what's in div, but ignores anything what's inside a fieldset.

The page is very long so it obviously takes time to render it, but when it's done, it has only two div elements on it. Page has like a dozen of long fieldsets and they are all ignored.

I am using this library on Drupal, this module is supported by https://www.drupal.org/project/print

![image](https://user-images.githubusercontent.com/62036912/137022653-44f3896c-ece5-4af1-970f-9560e0fd8b1e.png)

![image](https://user-images.githubusercontent.com/62036912/137022673-2cfd469d-1b43-4fba-992e-4c0741650402.png)

**Comment by fschutt** [comment]
I think you have the wrong repository, this repository has nothing to do with Drupal, this is a Rust library which happens to have the same name as the Drupal print project.

https://www.drupal.org/project/print/issues/3243165 is the correct place to ask.
