### ISSUE TITLE
docs.rs build failed for 0.5.2

### ISSUE THREAD

**Issue by jaskij** [sharazam/printpdf#117]
I'm just a passerby checking your crate out on docs.rs, and it seems like the docs failed:

![image](https://user-images.githubusercontent.com/1429132/161160759-954d81ca-607a-4fb7-8938-2d8450fe81fa.png)

**Comment by fschutt** [comment]
yeah, you need to use the docs for the 0.5.1 version: https://docs.rs/printpdf/0.5.1/printpdf/

I haven't had the time to fix this yet

**Comment by fschutt** [comment]
Probably fixed now.
