### ISSUE TITLE
PartialEq implementation of Mm fails for zero

### ISSUE THREAD

**Issue by jannschu** [sharazam/printpdf#137]
Hi,

this fails:

```rust
assert_eq!(Mm(0.), Mm(0.);
```

The issue is that in `impl_partialeq` the check `is_normal` returns false for zero.

**Comment by JulienSchminke** [comment]
Hi, I have fixed the bug. So I need to know how to push that to this repo now.
This is my first contribution on an open source project.

May I get some help how to do now?

Thanks :D

**Comment by jannschu** [comment]
Thanks for working on this @JulienSchminke! :-)

**Comment by JulienSchminke** [comment]
No Problem :D

I think we can close this issue after upload

**Comment by JulienSchminke** [comment]
Hey, my solution is merged now. So we can close this issue now.
