### ISSUE TITLE
Clarify function input units using Pt or Mm struct

### ISSUE THREAD

**Issue by SadCl0wn** [sharazam/printpdf#140]
Hello,
I've noticed that some functions like set_outline_thickness takes a f64 argument for the outline thickness. It's not clear whether the input is in points or millimeters. I propose to use Pt or Mm struct (could be an enum?) to clarify the input units, like so:

```rust
pub fn set_outline_thickness(&self, outline_thickness: Pt)
```

I believe that this change would make the library clearer and reduce potential errors caused by unit confusion.
I understand that this is a breaking change, but I think it would be worth it eventually. What do you think?

If you're okay with the proposal, I'd be happy to create a pull request with the necessary changes
thanks for your lib ^^

**Comment by OlivierLemoine** [comment]
Or in a less breaking manner:
```rust
pub fn set_outline_thickness<T: Into<Pt>>(&self, outline_thickness: T)
```

**Comment by fschutt** [comment]
In the `0.8` API, all `Op`s now use units:

```rust
    /// Sets the outline thickness for texts / lines / polygons
    SetOutlineThickness { pt: Pt },
```
