### ISSUE TITLE
target wasm32 is using stdweb

### ISSUE THREAD

**Issue by eribol** [sharazam/printpdf#144]
I am not sure which package tring to install stdweb but lopdf and printpdf using time package and somehow it install stdweb 0.4.2 which it is not compatible with syn v2. It only depends on wasm32 target.

**Comment by LiamPClancy** [comment]
I've also had a look at this and resolved it on my local branch, 
I upgraded lopdf to 0.31.0
I upgraded time to 0.3.25

the upgrade to lopdf required me to change most if not all the f64 in the crate to f32 to be compatible with the 0.31.0 version, 
it now builds for me and the very basic functionality I was using is working again. 

if you add permissions for my user I can push up the branch where I have resolved it?

**Comment by fschutt** [comment]
@learnplaycreate You can make your own branch and create a PR, I can merge from there, you don't need to wait for permission that's the point of forking.

**Comment by LiamPClancy** [comment]
done, sorry for the not forking move, 
don't do much open source work. 

https://github.com/fschutt/printpdf/pull/146
