### ISSUE TITLE
How To Use FontData for Calculating Width and Height of a Text

### ISSUE THREAD

**Issue by alpaylan** [sharazam/printpdf#145]
I wanted to use FontData for calculating width and height of a text so I can do layouting, but I couldn't figure out a way to do it. Is that possible?

**Comment by fschutt** [comment]
See here: https://github.com/fschutt/printpdf/issues/39#issuecomment-559118743

Font parsing / shaping is deliberately not part of printpdf, because it's very complex, I wrote `azul-text-layout` to do that: https://crates.io/crates/azul-text-layout

**Comment by alpaylan** [comment]
Thanks!
