### ISSUE TITLE
Hyperlinks

### ISSUE THREAD

**Issue by alpaylan** [sharazam/printpdf#148]
Hi, I would like to use hyperlinks where text has an embedded link in it, similar to href in Latex or <a> in HTML. What is the right way to do it?

**Comment by fschutt** [comment]
Sorry, I don't know.

**Comment by alpaylan** [comment]
> Sorry, I don't know.

Would it be okay if I tried to add a PR that does this?

**Comment by fschutt** [comment]
@alpaylan Yeah sure

**Comment by alpaylan** [comment]
[PR](https://github.com/fschutt/printpdf/pull/149) opened.

**Comment by alpaylan** [comment]
PR merged.
