### ISSUE TITLE
Can't print image in pdf

### ISSUE THREAD

**Issue by huand** [sharazam/printpdf#166]
Using the example image_alpha seems to work just fine as I can open the pdf and see the image for example in chrome
<img width="772" alt="ChromeOk" src="https://github.com/fschutt/printpdf/assets/12753392/7fd8e60e-2ae7-4135-b873-6ee3a1ea1023">

However when I try to open with AcrobatReader (version 23.008.20470), there is an error:
<img width="614" alt="AcrobatError" src="https://github.com/fschutt/printpdf/assets/12753392/a185c109-c86f-4c24-ab69-72b5ce46cb78">

And when trying to physically print, the page is just blank
<img width="780" alt="PrintBlank" src="https://github.com/fschutt/printpdf/assets/12753392/06a95bc7-76ef-4b43-a0b0-a1f8009d5c42">

Did someone manage to print an image this way? how did you manage? where is the issue coming from?

Thx!

**Comment by qarmin** [comment]
Also qpdf found some problems

```
cargo run --example image_alpha --features="embedded_images" --release
qpdf --check test_image.pdf
```
```
checking test_image.pdf
PDF Version: 1.3
File is not encrypted
File is not linearized
WARNING: test_image.pdf (object 7 0, offset 807): unknown token while reading object; treating as string
WARNING: test_image.pdf (object 7 0, offset 814): unknown token while reading object; treating as string
WARNING: test_image.pdf (object 7 0, offset 1115): unknown token while reading object; treating as string
WARNING: test_image.pdf (object 7 0, offset 1117): treating unexpected brace token as null
WARNING: test_image.pdf (object 7 0, offset 1118): unknown token while reading object; treating as string
WARNING: test_image.pdf (object 7 0, offset 1183): unknown token while reading object; treating as string
WARNING: test_image.pdf (object 7 0, offset 1183): too many errors; giving up on reading object
WARNING: test_image.pdf (object 7 0, offset 1195): expected endobj
qpdf: operation succeeded with warnings

```
