### ISSUE TITLE
Rotate text

### ISSUE THREAD

**Issue by agavrel** [sharazam/printpdf#177]
Hi,

Could you let me know if there is a way to rotate text?

Best regards,

**Comment by fschutt** [comment]
Use `set_text_matrix` inside of a `layer.begin_text_section()` / `layer.end_text_section()` block:

https://github.com/fschutt/printpdf/blob/fbc7d691f988b0d295570bee072de932f4cabda2/examples/font.rs#L50

**Comment by agavrel** [comment]
hello yes I had it figured out this weekend;) thanks!
