### ISSUE TITLE
makepdf, built on top of printpdf

### ISSUE THREAD

**Issue by chipsenkbeil** [sharazam/printpdf#187]
Wanted to introduce [makepdf](https://github.com/chipsenkbeil/makepdf), a binary where you write Lua scripts to build out PDFs, powered by the printpdf library!

Didn't see a discussion section enabled to share this, so added it as an issue. 😄 

Thanks for putting in so much work to build out this library!

**Comment by fschutt** [comment]
Yeah, this is what printpdf was intended.

I didn't want to support every possible feature of PDF, just the basic blocks so people can build on top.

Good work keep it up 👍
