### ISSUE TITLE
What can I do to make the font drawn through printpdf not the entire ttf be typed into the pdf, thereby reducing the size of the pdf

### ISSUE THREAD

**Issue by bianbiandashen** [sharazam/printpdf#195]
let font_ref = doc.add_external_font(File::open(&font_path).expect("无法打开字体文件")).unwrap();
is bad

**Comment by bianbiandashen** [comment]
<img width="1071" alt="image" src="https://github.com/user-attachments/assets/bbb61da0-42b8-4f9f-b361-8ced34dd9ba4">
<img width="1104" alt="image" src="https://github.com/user-attachments/assets/b1cae24e-5fa4-4b97-8efe-a63a4b38aa84">

**Comment by fschutt** [comment]
Use `allsorts::subset::subset(font, glyphs)` like in this function:

https://github.com/fschutt/printpdf/blob/5109221b158c767e621309d88afe5af56b11b168/src/font.rs#L322

Or wait for the 0.8 release (or use the master branch from GitHub directly).
