### ISSUE TITLE
In `0.7` this isn't possible (it will always embed the entire font), in `0.8` the default behaviour is to subset the font on save. In other words, just wait until `0.8` is released.

### ISSUE THREAD

**Issue by bianbiandashen** [sharazam/printpdf#196]
In `0.7` this isn't possible (it will always embed the entire font), in `0.8` the default behaviour is to subset the font on save. In other words, just wait until `0.8` is released.

_Originally posted by @fschutt in https://github.com/fschutt/printpdf/issues/189#issuecomment-2452938099_

0.8 Can I use it now? In addition, does the function of subset font also support windows?

**Comment by bianbiandashen** [comment]
Can you show your code and I can also work with you to build subsets?
In addition, even if 0.8 activates this ability   When adding_external_font, the cache capabilities should still need to be preserved, right?<img width="1043" alt="image" src="https://github.com/user-attachments/assets/4d97993c-59fe-4eff-b8f8-6b1680105028">

**Comment by fschutt** [comment]
You can use `printpdf = { git = „https://github.com/fschutt/printpdf“ }` in your Cargo.toml and look at the examples, they have been updated for the new version. Only minor bugs with SVGs and layers need to be worked out, the rest is the same API.

I am mainly working on the HTML renderer in 0.8, so it will still take some time to release (since 0.8 is the biggest refactoring in 5+ years, I don‘t want to rush it, I guess end of November it‘ll be stable enough).

**Comment by fschutt** [comment]
> When adding_external_font, the cache capabilities should still need to be preserved, right?

In 0.8 it uses a unique FontId String instead of a Rust reference to identify where a font was used in the document:

```rust
let mut doc = PdfDocument::new(„title“);
let font = ParsedFont::from_bytes(BYTES).unwrap();
let fontid = doc.add_font(&font); // random string

```

**Comment by fangqi5** [comment]
> https://github.com/fschutt/printpdf

Hi, my usage scenario is to draw PDF and print on Windows system, including win7/win10/win11. Does this code support the above systems?

**Comment by fangqi5** [comment]
Hi, my usage scenario is to draw PDF and print on Windows system, including win7/win10/win11. Does this code support the above systems?

**Comment by fangqi5** [comment]
> > When adding_external_font, the cache capabilities should still need to be preserved, right?
> 
> In 0.8 it uses a unique FontId String instead of a Rust reference to identify where a font was used in the document:
> 
> ```rust
> let mut doc = PdfDocument::new(„title“);
> let font = ParsedFont::from_bytes(BYTES).unwrap();
> let fontid = doc.add_font(&font); // random string
> ```

Hi  When I configure to download the code from git, the following error appears when running locally. My rust version is rustc 1.79.0 (129f3b996 2024-06-10)

**Comment by fschutt** [comment]
> Hi, my usage scenario is to draw PDF and print on Windows system, including win7/win10/win11. Does this code support the above systems?

Yes.

> Hi When I configure to download the code from git, the following error appears when running locally. My rust version is rustc 1.79.0 (129f3b996 2024-06-10)

Please post the error.

**Comment by fangqi5** [comment]
> > Hi, my usage scenario is to draw PDF and print on Windows system, including win7/win10/win11. Does this code support the above systems?
> 
> Yes.
> 
> > Hi When I configure to download the code from git, the following error appears when running locally. My rust version is rustc 1.79.0 (129f3b996 2024-06-10)
> 
> Please post the error.

error: unexpected token: `<-`
  --> /Users/fangqiji/.cargo/git/checkouts/printpdf-ad3d01efe2a6c4c7/c03ca60/src/types/plugins/graphics/two_dimensional/line.rs:93:45
   |
93 |                     operations.place_back() <- Operation::new(OP_PATH_PAINT_FILL_STROKE_CLOSE_NZ, vec![]);
   |                                             ^^
   |
help: if you meant to write a comparison against a negative value, add a space in between `<` and `-`
   |
93 |                     operations.place_back() < - Operation::new(OP_PATH_PAINT_FILL_STROKE_CLOSE_NZ, vec![]);
   |                                             ~~~

**Comment by fangqi5** [comment]
> > Hi, my usage scenario is to draw PDF and print on Windows system, including win7/win10/win11. Does this code support the above systems?
> 
> Yes.
> 
> > Hi When I configure to download the code from git, the following error appears when running locally. My rust version is rustc 1.79.0 (129f3b996 2024-06-10)
> 
> Please post the error.

```
error: unexpected token: `<-`
  --> /Users/fangqiji/.cargo/git/checkouts/printpdf-ad3d01efe2a6c4c7/c03ca60/src/types/plugins/graphics/two_dimensional/line.rs:93:45
   |
93 |                     operations.place_back() <- Operation::new(OP_PATH_PAINT_FILL_STROKE_CLOSE_NZ, vec![]);
   |                                             ^^
   |
help: if you meant to write a comparison against a negative value, add a space in between `<` and `-`
   |
93 |                     operations.place_back() < - Operation::new(OP_PATH_PAINT_FILL_STROKE_CLOSE_NZ, vec![]);
   |                                             ~~~


```

**Comment by fschutt** [comment]
@fangqi5 You are for some reason using a version `c03ca60`, a printpdf version from July **2017**. You don't need to download the code from git, just put this in your Cargo.toml:

```toml
printpdf = { git = "https://github.com/fschutt/printpdf", branch = "master" }
```

or:


```toml
printpdf = { git = "https://github.com/fschutt/printpdf", rev = "5109221b" } # todays commit
```


In 2017 the `place_back() <-` notation was allowed on nightly, that's why it doesn't compile anymore.

**Comment by fschutt** [comment]
@bianbiandashen and for future reference, please don‘t blindly copy code (or in this case version numbers) from ChatGPT, please use your brain instead

**Comment by fschutt** [comment]
@fangqi5 Next time, please don‘t blindly copy code (or in this case version numbers) from ChatGPT.

**Comment by fangqi5** [comment]
> ```toml
> rev
> ```

I sincerely apologize. While my Cargo.toml file configuration aligns with what you provided, the absence of the "cargo clean" step resulted in downloading code that did not meet expectations.

**Comment by fangqi5** [comment]
I've encountered an issue with allsorts font subsetting on Windows - the generated subset font files are invalid when opened. I've noticed this is related to [issue #27](https://github.com/yeslogic/allsorts/issues/27) on the allsorts repository. Are there any workarounds available for this problem?

**Comment by fangqi5** [comment]
Hi, I've come across [issue #27](https://github.com/yeslogic/allsorts/issues/27) in the allsorts repository where subsetting fonts on Windows results in invalid font files. I'm wondering if there are any workarounds available for this issue?

**Comment by fschutt** [comment]
@fangqi5 I am debugging the layout at the moment, it also seems that the kerning / layouting is off when using subset fonts... not sure why.

**Comment by bianbiandashen** [comment]
There is a great need for version 0.8 of [printpdf](https://github.com/fschutt/printpdf) to support font pumping technology. You should also use allsorts as a rust-based solution, right? There have been complaints that pdf is too big and will cause too long printing time.

**Comment by bianbiandashen** [comment]
@fschutt  "Could you please support this as soon as possible? The ability to reduce the font size in the PDF."

**Comment by bianbiandashen** [comment]
@fschutt Why not just use the default system font library to print PDF directly. . At least it won't be this slow. And the pdf will not be so big

**Comment by fschutt** [comment]
@bianbiandashen Because it's not cross-platform, especially because I want to support WASM.

**Comment by bianbiandashen** [comment]
@fschutt  
Is there a time point when it can be supported? Otherwise, the package produced by printpdf is indeed too large.

**Comment by fschutt** [comment]
@bianbiandashen The default fonts embedded in the PDF are about 50KB large: https://github.com/fschutt/printpdf/blob/master/defaultfonts/Times-Roman.subset.ttf and they're subsetted again, so the final embedded font ends up adding 5 - 10 KB. It can be optimized further, but it's not worth the effort right now.

The other fonts are subsetted now if you use the master branch: 

```toml
# Cargo.toml
printpdf = { git = "https://github.com/fschutt/printpdf", rev = "e8028073" }
```

**Comment by bianbiandashen** [comment]
let font_path = get_font_path("SimHei, Arial, sans-serif", "normal");
            let subset_font_path = font_path.to_string_lossy().into_owned();

            let rt = tokio::runtime::Builder::new_current_thread()
                .enable_all()
                .build().map_err(|e| format!("创建runtime失败: {}", e))?;

            rt.block_on(async {
                execute_component_main(&task_id_for_blocking, &json, &doc, page_width, page_height, (page1, layer1), subset_font_path).await;
            });       
execute_component_main is drawn directly through printpdf 。  
Do you mean that https://github.com/fschutt/printpdf/blob/master/defaultfonts/Times-Roman.subset.ttf can be replaced by ("SimHei, Arial, sans-serif", "normal"); @fschutt

**Comment by bianbiandashen** [comment]
> @bianbiandashen The default fonts embedded in the PDF are about 50KB large: https://github.com/fschutt/printpdf/blob/master/defaultfonts/Times-Roman.subset.ttf and they're subsetted again, so the final embedded font ends up adding 5 - 10 KB. It can be optimized further, but it's not worth the effort right now.
> 
> The other fonts are subsetted now if you use the master branch:
> 
> ```toml
> # Cargo.toml
> printpdf = { git = "https://github.com/fschutt/printpdf", rev = "e8028073" }
> ```

@fschutt hello If I embed a custom font instead of using your default font, can I achieve the effect of automatic subsetting? The fonts I put here are "SimHei, Arial, sans-serif", "normal" because I need to support Chinese @fschutt

**Comment by fschutt** [comment]
> > @bianbiandashen The default fonts embedded in the PDF are about 50KB large: https://github.com/fschutt/printpdf/blob/master/defaultfonts/Times-Roman.subset.ttf and they're subsetted again, so the final embedded font ends up adding 5 - 10 KB. It can be optimized further, but it's not worth the effort right now.
> > The other fonts are subsetted now if you use the master branch:
> > ```toml
> > # Cargo.toml
> > printpdf = { git = "https://github.com/fschutt/printpdf", rev = "e8028073" }
> > ```
> 
> @fschutt hello If I embed a custom font instead of using your default font, can I achieve the effect of automatic subsetting? The fonts I put here are "SimHei, Arial, sans-serif", "normal" because I need to support Chinese @fschutt

Yes, they will be subsetted now. Just try it like here: https://github.com/fschutt/printpdf/blob/e802807355277bc2a0da6b4b57ef52a42a3c63d6/examples/simple.rs#L72-L130
