### ISSUE TITLE
insert a image  , some times only show half .

### ISSUE THREAD

**Issue by wjcroom** [sharazam/printpdf#200]
some times  some png  and bmp .  image  hide  bottom part image  a line splite .   some part is hidden . why ?     0.7.0 version   printpdf .

**Comment by wjcroom** [comment]
![截图20241204030742](https://github.com/user-attachments/assets/45a04348-5eab-422d-9a39-89d3340f1364)
only part of png show . when I trasate png  to bmp  ,use the BmpDecoder .   it is same 
my code is :
use printpdf::*;
use std::fs::File;
use std::io::BufWriter;
 
fn main() {
    println!("Hello, world!");

let (doc, page1, layer1) = PdfDocument::new("PDF_Document_title",  Mm(210.0),Mm(297.0), "Layer 1");
  let current_layer = doc.get_page(page1).get_layer(layer1);
 let mut image_file = File::open("metest.png").unwrap();
let image = Image::try_from( image_crate::codecs::png::PngDecoder::new(&mut image_file).unwrap()).unwrap();
image.add_to_layer(current_layer.clone(),  ImageTransform {
      
    //   scale_x:  Some( scale),
      // scale_y:   Some( scale ),
       translate_x: Some(Mm(8.0)),
       translate_y: Some(Mm(8.0)),
       ..Default::default()
   },);
 
 

  doc.save(&mut BufWriter::new(File::create("test_working.pdf").unwrap())).unwrap(); 


}

and i user  printpdf 07.
`[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2021"

[dependencies]
printpdf = { version = "0.7.0", features = [ "embedded_images" ] }`

**Comment by fschutt** [comment]
I know this happened once because of a bug in the image library, but that was years ago.

Can you send the broken PDF?

Can you run the `--example image` from master with your image?

**Comment by wjcroom** [comment]
OK ,I will  send the png ,and a bmp ,the pdf. to this project .  if the png file ,edit. export to bmp,  the error is represent .same .
so a change my image to  jpeg . then  repair the error .  all is show .
so i think the png ,color type system, or  transparency  is not correct anayle in printpdf  code .

**Comment by wjcroom** [comment]
https://github.com/wjcroom/hi/blob/master/%E5%BC%80%E5%8F%91%202.zip
I post all my test image in zip. pdf in zip is good，metest2.png is good。othe image with rgba withAlpha chanel，will break pdf。
 https://github.com/wjcroom/hi/blob/master/test_workingrrrr.pdf
this my broken pdf，
and i find metest2.png rgb is ok , metest.png  rgba is  error.

i export a mettest.bmp with bmpotion    it is half  hidden. too. 
PNG supports translucency, if clear it .it is ok .maybe can find a correct way to use it in pdf file .

**Comment by wjcroom** [comment]
![Uploading pngoptions.jpg…]()

**Comment by wjcroom** [comment]
![Uploading pngoptions.jpg…]()

**Comment by wjcroom** [comment]
@fschutt  the same pdf file .I chage a machine ,it is show ..........at last ,it is my os bug???
it is relate to pdf reader ,  in. win10. chrom 115,  and. ubuntu 24.04  mac os 114 hidden half .
the same img pdf  in mac  os chrome   131.0. can show img noramlly.
at last ,
the image source  with   Alpha  chanel  off  will be ok. 
with Alpha chanel on  will be hidden partly.

**Comment by wjcroom** [comment]
![Uploading pngoptions.jpg…]()

**Comment by wjcroom** [comment]
![pngoptions2](https://github.com/user-attachments/assets/e5d44096-4acf-4e8e-b96f-ce4a78e5d436)
this is my gimp options for png

**Comment by wjcroom** [comment]
https://gitlab.mister-muffin.de/josch/img2pdf
  png 2 pdf work fine .so  it say **In most cases, the PNG Paeth filter is applied to the pixel data.**
maybe it is useful for this fix.
`
def to_png_data(img):
--
  |   | # cheapo version to retrieve a PNG encoding of the payload is to
  |   | # just save it with PIL. In the future this could be replaced by
  |   | # dedicated function applying the Paeth PNG filter to the raw pixel
  |   | pngbuffer = BytesIO()
  |   | img.save(pngbuffer, format="png")
  |   |  
  |   | pngidat, palette = parse_png(pngbuffer.getvalue())
  |   | # PIL does not provide the information about the original bits per
  |   | # sample. Thus, we retrieve that info manually by looking at byte 9 in
  |   | # the IHDR chunk. We know where to find that in the file because the
  |   | # IHDR chunk must be the first chunk
  |   | pngbuffer.seek(24)
  |   | depth = ord(pngbuffer.read(1))
  |   | if depth not in [1, 2, 4, 8, 16]:
  |   | raise ValueError("invalid bit depth: %d" % depth)
  |   | return pngidat, palette, depth

`

**Comment by fschutt** [comment]
It does work without problem in the current master:

```toml
# Cargo.toml
printpdf = { git = "https://github.com/fschutt/printpdf", rev = "e8028073, features = ["png"] }
```

```rust
use printpdf::*;

fn main() {
    let mut doc = PdfDocument::new("My first PDF");
    let image_bytes = include_bytes!("metest.png");
    let image = RawImage::decode_from_bytes(image_bytes).unwrap(); // requires --feature bmp

    // In the PDF, an image is an `XObject`, identified by a unique `ImageId`
    let image_xobject_id = doc.add_image(&image);

    let page1_contents = vec![Op::UseXObject {
        id: image_xobject_id.clone(),
        transform: XObjectTransform::default(),
    }];

    let page1 = PdfPage::new(Mm(210.0), Mm(297.0), page1_contents);
    let pdf_bytes: Vec<u8> = doc.with_pages(vec![page1]).save(&PdfSaveOptions::default());
    let _ = std::fs::write("image.pdf", pdf_bytes);
}
```

Result: 

[image.pdf](https://github.com/user-attachments/files/18048708/image.pdf)

Whatever it was, it's fixed now.

**Comment by wjcroom** [comment]
i run your code again , it work . refix it.  then  how would we do with  bmp.

now i will  try it in wasm .  
yes fixed  png  and other two wasm documentinfo.rc err   on  wasm-runtime. .

I want to scale the image .i will  find some code . thanks ...
```

t XObjectTransform {
    pub translate_x: Option<Pt>,
    pub translate_y: Option<Pt>,
    /// Rotate (clockwise), in degree angles
    pub rotate: Option<XObjectRotation>,
```

yes i can scale  with this . but when width>heighte,. i need  rotate.   traslate_x   use  Pt.
and  XObjectRotation   center_x  use  px  type .
i  can't find a correct  center x, y.    if it is image.width?   pix,   i guess it is pixsel    with a f32 type . yes I would * the scale to it . (i made a misttake .)
finally   cannsel    rotate.  i change the page  with 297,height  210.

 I will find  center  of a image ??with px ..............ok  that is all  

thanks  for your codes
